name: mlb_pitch_analytics
version: 1.0.0
config-version: 2

profile: mlb_pitch_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  mlb_pitch_analytics:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: silver
      +tags: ["silver"]
    intermediate:
      +schema: silver
      +tags: ["silver", "incremental"]
    marts:
      +materialized: table
      +schema: gold
      +tags: ["gold", "mart"]

seeds:
  mlb_pitch_analytics:
    +schema: reference
    +quote_columns: false
